//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradores
    {
        public int IdUsuario { get; set; }
        public Nullable<int> Nivel { get; set; }
        public int IdEmpresa { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
