//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imss
    {
        public int IdImss { get; set; }
        public Nullable<int> IdRegistroPatronal { get; set; }
        public Nullable<byte> ReportadoPorCandidato { get; set; }
        public string NombreDioReferencias { get; set; }
        public string PuestoDeQuienDioReferencias { get; set; }
        public string TelefonoDeQuienDioReferencias { get; set; }
        public string EmailDeQuienDioReferencias { get; set; }
        public string MotivoSalida { get; set; }
        public string PuestoInicial { get; set; }
        public string PuestoFinal { get; set; }
        public string Referencia { get; set; }
        public Nullable<byte> PertenecioSindicato { get; set; }
    
        public virtual RegistrosPatronales RegistrosPatronales { get; set; }
    }
}
