//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public string IdParametro { get; set; }
        public Nullable<System.TimeSpan> HoraCorteAtencion { get; set; }
        public string CorreoParaEnvio { get; set; }
        public string CorreoContrasena { get; set; }
    }
}
