//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosPatronales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrosPatronales()
        {
            this.CartaIndividual = new HashSet<CartaIndividual>();
            this.Imss = new HashSet<Imss>();
        }
    
        public int IdRegistroPatronal { get; set; }
        public int IdSolicitud { get; set; }
        public string RegistroPatronal { get; set; }
        public string NombreCompania { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartaIndividual> CartaIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imss> Imss { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
