//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes()
        {
            this.ReferenciasLaborales = new HashSet<ReferenciasLaborales>();
            this.RegistrosPatronales = new HashSet<RegistrosPatronales>();
            this.SolicitudesArchivos = new HashSet<SolicitudesArchivos>();
        }
    
        public int IdSolicitud { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPatermo { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Puesto { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string TelefonoCelular { get; set; }
        public string TelefonoCasa { get; set; }
        public string TelefonoRecados { get; set; }
        public string Calle { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string AlcaldiaMunicipio { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> IdEmpresaFacturar { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string UploadFileName { get; set; }
        public Nullable<System.DateTime> FechaCaptura { get; set; }
        public Nullable<System.DateTime> FechaAtencion { get; set; }
        public Nullable<int> IdUsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string ImssFile { get; set; }
        public string emailCandidato { get; set; }
        public string observaciones { get; set; }
        public string SolicitadoPor { get; set; }
        public string sexo { get; set; }
        public string FaceBook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public decimal SueldoAspirado { get; set; }
        public decimal TiempoEstimadoTraslado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual EmpresasFacturar EmpresasFacturar { get; set; }
        public virtual Estatus Estatus { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenciasLaborales> ReferenciasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrosPatronales> RegistrosPatronales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesArchivos> SolicitudesArchivos { get; set; }
    }
}
