//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesArchivos
    {
        public int IdSolicitudArchivo { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public string AvisoPrivacidad { get; set; }
        public string INE { get; set; }
    
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
