//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmpresas
    {
        public int IdEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string CodigoRegistro { get; set; }
        public int IdEstatus { get; set; }
        public string Estatus { get; set; }
    }
}
