//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vReferenciasLaborales
    {
        public int IdReferenciaLaboral { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaAnteriorIngreso { get; set; }
        public string FamiliaenEmpresa { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAnteriorEgreso { get; set; }
        public string Nombre { get; set; }
        public string TrabajoAntesEmpresa { get; set; }
        public int IdReferenciaLaboralD { get; set; }
        public string NombreEmpresa { get; set; }
        public string Sucursal { get; set; }
        public string Outsourcing { get; set; }
        public string GiroEmpresa { get; set; }
        public string MarcaAsignada { get; set; }
        public string DomicilioLaboral { get; set; }
        public string PuestoDesempeñado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public string MotivoSalida { get; set; }
        public string CartaRecomendacion { get; set; }
        public string JefeInmediato { get; set; }
        public string Telefonos { get; set; }
        public string ObservacionesD { get; set; }
        public string Puesto { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string TelefonoCelular { get; set; }
        public string TelefonoCasa { get; set; }
        public string NumExterior { get; set; }
        public string NumInterior { get; set; }
        public string Colonia { get; set; }
        public string Calle { get; set; }
        public string CodigoPostal { get; set; }
        public string AlcaldiaMunicipio { get; set; }
        public string Ciudad { get; set; }
        public string emailCandidato { get; set; }
        public string Nombre_Empresa_a_Laborar { get; set; }
    }
}
