//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegistrosPatronales
    {
        public int IdRegistroPatronal { get; set; }
        public int IdSolicitud { get; set; }
        public string RegistroPatronal { get; set; }
        public string NombreCompania { get; set; }
    }
}
