//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSolicitudes
    {
        public int IdSolicitud { get; set; }
        public string Candidato { get; set; }
        public string Puesto { get; set; }
        public string NombreComercial { get; set; }
        public string FechaCaptura { get; set; }
        public string FechaAtencion { get; set; }
        public string CURP { get; set; }
        public string IMSS { get; set; }
        public string ImssFile { get; set; }
        public string Nombre { get; set; }
        public string emailCandidato { get; set; }
        public string Estatus { get; set; }
    }
}
