//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImssAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUsuarios
    {
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string RazonSocial { get; set; }
        public string Contrasena { get; set; }
        public string Email { get; set; }
        public string Estatus { get; set; }
    }
}
